version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - node/test
      - codecov/upload:
          file: {{coverage_report_filepath}}
